export const DESKTOP_CHANNELS = {
  getServicesStatus: "get_services_status",
  startAllServices: "start_all_services",
  stopAllServices: "stop_all_services",
  restartService: "restart_service",
  getServiceLogs: "get_service_logs",
  getAgentServerInfo: "get_agent_server_info",
  getShellStatus: "desktop_shell_status",
  listServiceDescriptors: "list_service_descriptors",
  registerServiceDescriptor: "register_service_descriptor",
  unregisterServiceDescriptor: "unregister_service_descriptor",
  selectDirectory: "select_directory",
  openExternalUrl: "open_external_url",
  appQuit: "app_quit",
  windowOpenNew: "window_open_new",
  windowMinimize: "window_minimize",
  windowMaximize: "window_maximize",
  windowClose: "window_close",
  windowIsMaximized: "window_is_maximized",
  windowReload: "window_reload",
  windowToggleDevTools: "window_toggle_devtools",
  windowToggleFullscreen: "window_toggle_fullscreen",
  cliLoginStatus: "cli_login_status",
  cliLoginLaunch: "cli_login_launch",
  cliInstallStatus: "cli_install_status",
  cliInstallToPath: "cli_install_to_path",
  cliUninstallFromPath: "cli_uninstall_from_path",
  updaterCheck: "updater:check",
  updaterDownload: "updater:download",
  updaterQuitAndInstall: "updater:quit-and-install",
  updaterShowWindow: "updater:show-window",
  updaterGetState: "updater:get-state",
} as const;

export const DESKTOP_EVENTS = {
  serviceStatusChanged: "service-status-changed",
  serviceDescriptorsChanged: "service-descriptors-changed",
  updaterChecking: "updater:checking",
  updaterAvailable: "updater:available",
  updaterNotAvailable: "updater:not-available",
  updaterProgress: "updater:progress",
  updaterDownloaded: "updater:downloaded",
  updaterError: "updater:error",
} as const;
