"""OpenUI generative-UI prompt assembly.

The ``genui-lib`` system prompt is vendored as a package asset (regenerated by
``frontend/packages/ui/scripts/gen_openui_prompt.mjs``); here we splice it with
the agent's request (+ optional data) into the single user turn sent to the
ephemeral generative-UI session.
"""

from __future__ import annotations

import json
from importlib import resources

TOOL_DESCRIPTION = (
    "Generate a rich, interactive UI — charts, tables, forms, KPI cards, or a "
    "dashboard — when a visual component would communicate the answer more "
    "clearly than prose. Pass a natural-language `request` describing what to "
    "show, and optional `data` (structured values to render directly). Do NOT "
    "call this for ordinary Q&A that text answers well. The tool returns OpenUI "
    "Lang that the client renders inline; do not repeat the same content as "
    "text afterwards."
)

GENERATIVE_UI_INSTRUCTIONS = (
    "You generate user interfaces in OpenUI Lang. Output ONLY valid OpenUI Lang "
    "using the components described in the library below — no prose, no code "
    "fences, no explanations. Render the requested information directly into the "
    "components."
)


def _load_library_prompt() -> str:
    return (
        resources.files(__package__)
        .joinpath("openui_genui_lib_prompt.txt")
        .read_text(encoding="utf-8")
    )


def build_openui_prompt(request: str, data: object | None = None) -> str:
    parts = [
        GENERATIVE_UI_INSTRUCTIONS,
        "",
        _load_library_prompt(),
        "",
        "REQUEST:",
        request.strip(),
    ]
    if data is not None:
        parts.append("")
        parts.append("DATA (render these values directly into the components):")
        parts.append(json.dumps(data, ensure_ascii=False))
    return "\n".join(parts)
