"""OpenUI generative-UI prompt assembly.

The ``genui-lib`` system prompt is vendored as a package asset (regenerated by
``frontend/packages/ui/scripts/gen_openui_prompt.mjs``); here we splice it with
the agent's request (+ optional data) into the single user turn sent to the
ephemeral generative-UI session.
"""

from __future__ import annotations

import json
from importlib import resources

TOOL_DESCRIPTION = (
    "Generate a rich, interactive UI — charts, tables, forms, KPI cards, or a "
    "dashboard — when a visual component would communicate the answer more "
    "clearly than prose. Pass a natural-language `request` describing what to "
    "show, and optional `data` (structured values to render directly). Do NOT "
    "call this for ordinary Q&A that text answers well. The tool returns OpenUI "
    "Lang that the client renders inline; do not repeat the same content as "
    "text afterwards."
)

GENERATIVE_UI_INSTRUCTIONS = (
    "You generate user interfaces in OpenUI Lang. Output ONLY valid OpenUI Lang "
    "using the components described in the library below — no prose, no code "
    "fences, no explanations. Render the requested information directly into the "
    "components. For Valuz desktop layouts, do not nest Card components. Prefer "
    "borderless sections separated by spacing or Separator, and use an unframed "
    "row or table for related metrics. Use a Card only for a genuinely framed "
    "repeated item or an isolated secondary surface."
    " The result is embedded inside an existing conversation pane: never generate "
    "an application shell, sidebar, top navigation, user menu, or fixed-width "
    "page chrome. The root must be a compact column layout that fits its parent. "
    "Use a mobile-first responsive layout: the root should be "
    "Stack(..., \"column\", ...), but do not force every module to occupy a "
    "full-width row. Peer modules may share wrapping rows or responsive grids "
    "when there is room, then stack on narrow screens. For text-heavy content, "
    "avoid narrow sidebars and use columns only when every column remains "
    "readable; insights, concepts, notes, and explanations may sit beside "
    "related content on wide layouts, but must be able to wrap below it. Every "
    "row/grid must set wrap=true and must wrap before they overflow. Keep each "
    "item readable on narrow screens; never use writing-mode, rotated text, or "
    "columns that force CJK/English words to break one character per line. "
    "Prefer Table, Accordion, Tabs, or grouped card rows when many categories "
    "compete for horizontal space. "
    "For dashboards, KPI metrics may use a wrapping row, but charts must render "
    "one per row at full available width. Never place two or more charts side by "
    "side; use Tabs to switch between multiple chart views. Never use fixed pixel "
    "widths. Keep chart labels concise and limit a chart to the most useful six "
    "categories, grouping the remainder as Other."
)


def _load_library_prompt() -> str:
    return (
        resources.files(__package__)
        .joinpath("openui_genui_lib_prompt.txt")
        .read_text(encoding="utf-8")
    )


def build_openui_prompt(request: str, data: object | None = None) -> str:
    parts = [
        GENERATIVE_UI_INSTRUCTIONS,
        "",
        _load_library_prompt(),
        "",
        "REQUEST:",
        request.strip(),
    ]
    if data is not None:
        parts.append("")
        parts.append("DATA (render these values directly into the components):")
        parts.append(json.dumps(data, ensure_ascii=False))
    return "\n".join(parts)
